apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin-sidecar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WorldDrknss/argocd-vault-plugin.git
    targetRevision: main
    path: "."
    directory:
      exclude: '{values.yaml,LISCENSE,README.md,manifests/*,merge/*}'  # Exclude unnecessary files
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
