apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/cmp-plugin.yaml
  - manifests/role.yaml
  - manifests/role-binding.yaml

patches:
  - path: merge/argocd-repo-server.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
